---
title: "git_01"
author: "Diana Reyes"
date: "September 8,2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->  
Learn well your grammar,  

And never stammar,  

Write well and neatly,  

And sing most sweetly,  

Be enterprising,  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
'The wonder is I didn't see at once.  
I never noticed it from here before.  
I must be wonted to it--that's the reason.  
The little graveyard where my people are!  
So small the window frames the whole of it.  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,  
Shining with all his might:  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

This is not a small love  
you hear this is a large  
love, a passion for kissing learning  
on its face.  
This is a love that crowns the feet with hands  
that nourishes, conceives, feels the water sails  
mends the children,  
folds them inside our history where they  
toast more than the flesh  
where they suck the bones of the alphabet  
and spit out closed vowels.  
